apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: parser
    tier: backend
  name: parser
  namespace: yasp
spec:
  replicas: 1
  selector:
    app: parser
    tier: backend
  template:
    metadata:
      labels:
        app: parser
        tier: backend
    spec:
      volumes:
      - name: api-keys
        secret:
          secretName: api-keys
      containers:
      - name: yasp
        image: yasp/yasp:latest
        args: [ "node", "parser.js" ]
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "900m"
            memory: "200M"
        volumeMounts:
        - name: api-keys
          readOnly: true
          mountPath: /etc/yasp-api-keys
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
----
apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: parser
  namespace: yasp
spec:
  scaleRef:
    kind: ReplicationController
    name: parser
    subresource: scale
  minReplicas: 1
  maxReplicas: 100
  cpuUtilization:
    targetPercentage: 75