var async = require("async"),
    utility = require('./utility'),
    matches = utility.matches,
    players = utility.players,
    logger = utility.logger,
    moment = require('moment'),
    fs = require('fs'),
    jobs = utility.jobs;
var trackedPlayers = {};
var UNTRACK_INTERVAL_DAYS = process.env.UNTRACK_INTERVAL_DAYS || 3;