FROM node:20-alpine

# RUN apk add --no-cache curl

ENV NPM_CONFIG_LOGLEVEL warn

# COPY . /usr/src
# WORKDIR /usr/src
# RUN npm run build

COPY proto /usr/src/proto
COPY svc/retriever.ts /usr/src/svc/retriever.ts
COPY config.ts /usr/src/config.ts
WORKDIR /usr/src
RUN npm install dotenv@16.3.1 compression@1.7.4 express@4.18.2 tsx@4.6.2 steam-user@5.0.4 protobufjs@7.2.5 axios@1.6.3

ENV PATH /usr/src/node_modules/.bin:$PATH

ENV ROLE retriever

CMD ["tsx",  "svc/retriever.ts"]
