export const PRIORITY = {
  AUTO_TRACKED_PLAYER: -11,
  AUTO_LEAGUE: -10,
  REQUEST_SUBSCRIBER: -2,
  REQUEST_UI: -1,
  REQUEST_DEFAULT: 0,
  REQUEST_API_KEY: 1,
  AUTO_DEFAULT: 10,
  REQUEST_ALREADY_PARSED: 20,
};
