export const PRIORITY = {
  AUTO_LEAGUE: -6,
  AUTO_TRACKED_PLAYER: -5,
  REQUEST_SUBSCRIBER: -4,
  REQUEST_UI: -3,
  REQUEST_DEFAULT: -2,
  REQUEST_API_KEY: -1,
  AUTO_DEFAULT: 0,
  AUTO_GCDATA: 1,
  REQUEST_ALREADY_PARSED: 9,
};
