apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: fullhistory
    tier: backend
  name: fullhistory
  namespace: yasp
spec:
  replicas: 1
  selector:
    app: fullhistory
    tier: backend
    role: core
  template:
    metadata:
      labels:
        app: fullhistory
        tier: backend
        role: core
    spec:
      volumes:
      - name: api-keys
        secret:
          secretName: api-keys
      containers:
      - name: yasp
        image: yasp/yasp:latest
        args: [ "node", "fullhistory.js" ]
        imagePullPolicy: Always
        volumeMounts:
        - name: api-keys
          readOnly: true
          mountPath: /etc/yasp-api-keys
      restartPolicy: Always
