ALTER USER postgres PASSWORD 'postgres';
CREATE ROLE readonly PASSWORD 'readonly';
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonly;
CREATE DATABASE yasp;